<% puts "WARNING: PostgreSQL support is incomplete at this time, use at your own risk!" unless $dyW; $dyW = true %>
# PostgreSQL. Versions 7.4 and 8.x are supported.
#
# Install the ruby-postgres driver:
#   gem install ruby-postgres
# On Mac OS X:
#   gem install ruby-postgres -- --include=/usr/local/pgsql
# On Windows:
#   gem install ruby-postgres
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.

common: &common
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['USER'] %>
  password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432
  #
  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

development:
  database: calagator_dev
  << : *common

preview:
  database: calagator_dev
  << : *common

test:
  database: calagator_test
  << : *common

production:
  database: calagator_prod
  << : *common
