common: &common
  adapter: mysql
  encoding: utf8
  socket: <%= `mysql_config --socket`.chomp %>
  username: #TODO: create new user for calagator
  password: #TODO

development:
  database: calagator_dev
  << : *common

preview:
  database: calagator_dev
  << : *common

test:
  database: calagator_test
  << : *common

production:
  database: calagator_production
  << : *common